FROM golang:1.26.5-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /dummy-esp ./cmd/dummy/esp.go

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /dummy-esp .

ENTRYPOINT ["./dummy-esp"]
