# /etc/mosquitto/conf.d/bridge.conf

connection aws-bridge
address 100.84.119.64:8883
bridge_protocol_version mqttv311

remote_username esp32_user
remote_password # SUPER_SECRET_PASSWORD

topic celosia_bucket/# both 1

cleansession false
notifications false
start_type automatic

restart_timeout 5 30
